orcestra-campaign/pyorcestra

orcestra/sat.py
Rough implementation for loading sattelite tracks from https://github.com/orcestra-campaign/sattracks
=> basic sattrack loader

orcestra/weathermaps.py
Same request as for sat_image but now only containing the satellite plot.
=> Sat image (now as separate pull request)

orcestra/flightplan.py
This PR adds a function to open MSS flightplans in FTML format and return them as an xarray dataset.
I added the function to the `orcestra.flightplan` module because it seemed like the best place for it thematically. However, I am happy to move it if you want to keep your flightplan implementation separate.
=> Add function to open MSS flight tracks (FTML)

orcestra/sat.py
This is in anticipation of orcestra-campaign/sattracks#1.
=> sattracks: new column names

orcestra/__init__.py, orcestra/flightplan.py
These changes will make the flightplans in the ORCESTRA book nicer:
* less warnings
* better image resolution
* better text annotations
* less code (no explicit map extent required)
=> Nicer flightplans

orcestra/flightplan.py
The function includes the option to set the precision as FX can only use values rounded to minutes but for the EarthCARE coordination we can provide the pilots with higher resolution information.
=> Includes function to get waypoint in the way FX can handle directly.

orcestra/flightplan.py, pyproject.toml
This adds KML and geojson export
closes #27
=> flightplan export

orcestra/flightplan.py, tests/test_rounding.py
This adds the rounding / formatting functions
* `format_5min`
* `format_1min`
* `format_min100`
* `format_pilot`
and removes the ambiguous and occasionally imprecise `to_fx_format`.
=> flightplan LatLon: add rounding functions

orcestra/flightplan.py
This change allows to specify a time-point for a single waypoint within one path. If present, and if performance data is present, this will compute the approximate time for every waypoint.
=> flightplan: enable time annotation

orcestra/postprocess/level0.py, orcestra/postprocess/level1.py, pyproject.toml
Fixes the time coordinate of the radiometer data while keeping 4 Hz resolution in level0 processing. Adds function to resample radiometer data fast, by relying on pandas.dataframe.resample() which is much faster than xarray.resample.
=> Fix radiometer time

orcestra/flightplan.py
This function takes a satellite track and computes at which time the satellite crosses a certain latitude.
=> flightplan: add ec_time_at_lat

orcestra/postprocess/level1.py
Update pandas radiometer resample function to work with updated variable names. Variable names are not hardcoded anymore, except for TB.
=> Pandas radiometer resample fix

orcestra/weathermaps.py
This is assuming we have a gridded dropsonde dataset
=> overlay dropsondes on weather map

orcestra/flightplan.py
When called last in a notebook cell, this function adds two buttons to download GeoJSON and KML versions of the flight plan.
=> add export_flightplan

orcestra/flightplan.py
I thought this would be something you could also use in the HAMP repo .. hence pinging you to review.
=> added an overpass time estimator

orcestra/flightplan.py
30 points seemd to be a little low, thus changing to 90
=> flightplan: more interpolated points on circle

orcestra/flightplan.py
This function allows to get a `LatLon` point based on a track.
Optionally, the point can copy the interpolated `time` along the track.
=> flightplan: add point_on_track

orcestra/postprocess/level0.py, orcestra/postprocess/level1.py
Adds processing functions explicitly for IWV, including filtering of unrealistic spikes due to liquid clouds.
=> Remove IWV Spikes

orcestra/sat.py
I have added a simple loader for PACE. Florian also wanted to include PACE into his repository so maybe we don't need this but it helped me to get a good overview of where PACE for the next days would be.
=> Adds PACE loader

orcestra/flightplan.py
This PR introduces the `_in` waypoint at the beginning of a circle in the TXT output as a helper waypoint, *iff* the circle is not entered at 90°, as in this case, flying towards the circle center before entering the circle wouldn't be correct. The PR also rewords the description of how to fly into the circle slightly (it add's a note if we'd like to fly through the circle first). I also re-checked how we currently compute the direction from where to enter the circle, and indeed, we compute the position on the circle, not the direction on which the aircraft flies towards the circle (as we want).
fixes #67
fixes #68
=> reword details for circles which are not directly on flight track

orcestra/flightplan.py
This PR declutters the flight maps by removing unimportant labelled points.
fixes #69
=> FlightPlan: remove useless _in and _out waypoints from map

orcestra/flightplan.py, pyproject.toml
There is still an implicit healpy dependency through easygems which needs to be resolved there (e.g. https://github.com/mpimet/easygems/pull/18)
=> Remove explicit healpy dependency

orcestra/flightplan.py
function to get the intersection points of two circles. I haven't written any tests yet, so I am not sure if it is sufficient like this...
=> circle intersect

orcestra/flightplan.py
New distance function in LatLon to return distance between one LatLon instance and another
=> New distance function in LatLon

orcestra/flightplan.py
The BCO coordinates were wrongly pointing to the BGI airport. I changed them to the actual BCO located at the east coast of the island.
=> correct BCO LatLon

orcestra/flightplan.py
This closes https://github.com/orcestra-campaign/pyorcestra/issues/91
=> return lines from plot_fir

.pre-commit-config.yaml
=> adjust ruff to newer version

orcestra/sat.py
The function downloads a GOES image with predefinded corner coordinates and saves it under a comprehensive file name.
=> Includes a function to help the ground support downloading sat images.

orcestra/sat.py
The new implementation consists of two functions, one to retrieve the image and keep it in memory, and one to store it as JPG as before.
=> Refactor GOES snapshot

orcestra/io.py
This PR:
* fixes problems with date changes during HALO flights
* makes the parsing of IGI files more flexible in case of things...
=> Fix IGI parsing
